<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Collection of Studies</title>
  <meta name="description" content="A collection of my papers, interests, and studies.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="A Collection of Studies" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A collection of my papers, interests, and studies." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Collection of Studies" />
  
  <meta name="twitter:description" content="A collection of my papers, interests, and studies." />
  

<meta name="author" content="Nik Počuča">


<meta name="date" content="2018-10-07">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ss.html">
<link rel="next" href="understanding-the-em-algorithm.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Self Studies </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#updates"><i class="fa fa-check"></i>Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ss.html"><a href="ss.html"><i class="fa fa-check"></i><b>1</b> Self Studies</a></li>
<li class="chapter" data-level="" data-path="god-hates-rich-people.html"><a href="god-hates-rich-people.html"><i class="fa fa-check"></i>God Hates Rich People</a><ul>
<li class="chapter" data-level="" data-path="god-hates-rich-people.html"><a href="god-hates-rich-people.html#introduction-1"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="god-hates-rich-people.html"><a href="god-hates-rich-people.html#preliminary-analysis"><i class="fa fa-check"></i>Preliminary Analysis</a><ul>
<li class="chapter" data-level="" data-path="god-hates-rich-people.html"><a href="god-hates-rich-people.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="god-hates-rich-people.html"><a href="god-hates-rich-people.html#therefore-neither-rich-people-or-poor-people-are-more-likely-to-be-hit-with-extreme-weather-events."><i class="fa fa-check"></i>Therefore neither rich people or poor people are more likely to be hit with extreme weather events.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="understanding-the-em-algorithm.html"><a href="understanding-the-em-algorithm.html"><i class="fa fa-check"></i>Understanding the EM Algorithm</a><ul>
<li class="chapter" data-level="1.1" data-path="understanding-the-em-algorithm.html"><a href="understanding-the-em-algorithm.html#prologue"><i class="fa fa-check"></i><b>1.1</b> Prologue</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="seminars.html"><a href="seminars.html"><i class="fa fa-check"></i><b>2</b> Seminars</a><ul>
<li class="chapter" data-level="" data-path="seminars.html"><a href="seminars.html#modeling-invidiual-claims-with-a-cwm---oct-2nd-2018"><i class="fa fa-check"></i>Modeling Invidiual Claims with a CWM - Oct 2nd 2018</a></li>
<li class="chapter" data-level="" data-path="seminars.html"><a href="seminars.html#hacking-health---oct-19th-2017"><i class="fa fa-check"></i>Hacking Health - Oct 19th 2017</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Collection of Studies</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="god-hates-rich-people" class="section level1 unnumbered">
<h1>God Hates Rich People</h1>
<p>July 23, 2018</p>
<p>A self-study on extreme weather events locations vs Low/High Income locations.</p>
<div id="introduction-1" class="section level2 unnumbered">
<h2>Introduction</h2>
<p>Extreme weather events in the U.S. are regularly tracked by the National Oceanic and Atomspheric Administration (NOAA).</p>
<p>The NCDC Storm Events database is provided by the National Weather Service (NWS) and contain statistics on personal injuries and damage estimates. (ref. gov.noaa.ncdc:C00510).</p>
<div id="the-question-is-are-high-income-or-low-income-households-more-susceptible-to-extreme-weather-events" class="section level4 unnumbered">
<h4>The question is, are high-income or low-income households more susceptible to extreme weather events?</h4>
<p>The US Household Income dataset provided by Golden Oak Research Group contains 32,000 records on US Household Income Statistics &amp; Geo Locations. The dataset originally developed for real estate and business investment research. Income is a vital element when determining both quality and socioeconomic features of a given geographic location. (ref. Golden Oak Research Group, LLC. “U.S. Income Database Kaggle”. Publication: 5, August 2017.)</p>
</div>
</div>
<div id="preliminary-analysis" class="section level2 unnumbered">
<h2>Preliminary Analysis</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Loading packages
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(ggmap)
<span class="kw">library</span>(maps)
<span class="kw">library</span>(mapdata)

## Loading csv data. 
strmEvents &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;StormEvents_locations-ftp_v1.0_d2014_c20180718.csv&quot;</span>)

incomeKag &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;kaggle_income.csv&quot;</span>)


<span class="co"># load U.S, map and plot extreme events. </span>
usa &lt;-<span class="st"> </span><span class="kw">map_data</span>(<span class="st">&quot;usa&quot;</span>)
gg1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_polygon</span>(<span class="dt">data =</span> usa, <span class="kw">aes</span>(<span class="dt">x=</span>long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">coord_fixed</span>(<span class="fl">1.3</span>)

<span class="co"># I need to only get mainland U.S. </span>
onlyUS &lt;-<span class="st"> </span><span class="kw">subset</span>(strmEvents, (LONGITUDE <span class="op">&gt;</span><span class="st"> </span><span class="op">-</span><span class="dv">140</span> <span class="op">&amp;</span><span class="st"> </span>LONGITUDE <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span><span class="dv">50</span> <span class="op">&amp;</span><span class="st"> </span>LATITUDE <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span> <span class="op">&amp;</span><span class="st"> </span><span class="dv">20</span> <span class="op">&lt;</span><span class="st"> </span>LATITUDE ))

<span class="co"># Coordinate data preperation for plotting. </span>
corStrmEvents &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">lat =</span> onlyUS<span class="op">$</span>LATITUDE,
                            <span class="dt">long =</span> onlyUS<span class="op">$</span>LONGITUDE,
                            <span class="dt">names =</span> onlyUS<span class="op">$</span>EVENT_ID,
                            <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)

<span class="co"># Plotting</span>
gg1 <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> corStrmEvents, 
             <span class="kw">aes</span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="kw">exp</span>(<span class="op">-</span><span class="dv">100</span>))</code></pre></div>
<p><img src="self-studies_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>As we can see extreme weather events span the entire mainland U.S. Majority of the events are held along the eastern seaboard.</p>
<p>We then superimpose the dataset of US income where blue is the poverty line ( &lt; $25,000 USD) and green is the upper middle class ( $100,000 &gt; ).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">poorPeople &lt;-<span class="st"> </span><span class="kw">subset</span>(incomeKag, Lon <span class="op">&gt;</span><span class="st"> </span><span class="op">-</span><span class="dv">140</span> <span class="op">&amp;</span><span class="st"> </span>Mean <span class="op">&lt;</span><span class="st"> </span><span class="dv">25000</span> <span class="op">&amp;</span><span class="st"> </span>Lat <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span> <span class="op">&amp;</span><span class="st"> </span>Lat <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span>)

corPoorPeople &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">lat =</span> poorPeople<span class="op">$</span>Lat,
                              <span class="dt">long =</span> poorPeople<span class="op">$</span>Lon,
                              <span class="dt">names=</span> poorPeople<span class="op">$</span>Place,
                              <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)


richPeople &lt;-<span class="st"> </span><span class="kw">subset</span>(incomeKag, Lon <span class="op">&gt;</span><span class="st"> </span><span class="op">-</span><span class="dv">140</span> <span class="op">&amp;</span><span class="st"> </span>Mean <span class="op">&gt;</span><span class="st"> </span><span class="dv">100000</span> <span class="op">&amp;</span><span class="st"> </span>Lat <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span> <span class="op">&amp;</span><span class="st"> </span>Lat <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span>)

corRichPeople &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">lat =</span> richPeople<span class="op">$</span>Lat,
                            <span class="dt">long =</span> richPeople<span class="op">$</span>Lon,
                            <span class="dt">names =</span> richPeople<span class="op">$</span>Place,
                            <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)

gg2 =<span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_polygon</span>(<span class="dt">data =</span> usa, <span class="kw">aes</span>(<span class="dt">x=</span>long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">coord_fixed</span>(<span class="fl">1.3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>(<span class="dt">data =</span> corPoorPeople, 
           <span class="kw">aes</span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> <span class="st">&quot;Poverty Class&quot;</span>), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span>(<span class="dt">data =</span> corStrmEvents,
           <span class="kw">aes</span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> <span class="st">&quot;Extreme Weather Events&quot;</span>), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="fl">0.0001</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span>(<span class="dt">data =</span> corRichPeople,
           <span class="kw">aes</span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> <span class="st">&quot;Upper Middle Class&quot;</span>),<span class="dt">color =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) 
gg2 </code></pre></div>
<p><img src="self-studies_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>We can see that most of the green (rich) points are clustered around the major cities, while the blue (poor) points are fairly spread with some clumping.</p>
<p>Now we simply do a calculation of the minimum distance between every green point to red point, and then every blue point to red point. (ie, find the closest weather event to each income datapoint.)</p>
<p>To do this, I create a function called calcDistance which takes in a person, and a weather list object that has both longitude and latitude.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Calculate the distance for each poor person and rich person </span>
<span class="co"># to the nearest extreme weather event. </span>

calcDistance &lt;-<span class="st"> </span><span class="cf">function</span>(person,weather) {
  xE =<span class="st"> </span>weather<span class="op">$</span>long
  yE =<span class="st"> </span>weather<span class="op">$</span>lat 
  xS =<span class="st"> </span>person<span class="op">$</span>long 
  yS =<span class="st"> </span>person<span class="op">$</span>lat
  
  <span class="co"># Pythogram Theorem. (I know the earth is a curved surface but </span>
  <span class="co"># the curvature should be negligable if the locations are sufficiently close)</span>
  <span class="kw">return</span>(<span class="dt">distance =</span> (xE <span class="op">-</span><span class="st"> </span>xS)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span>(yE <span class="op">-</span><span class="st"> </span>yS)<span class="op">^</span><span class="dv">2</span>)
}

poorDistances &lt;-<span class="st"> </span><span class="kw">c</span>()
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(corPoorPeople[,<span class="dv">1</span>])){
  poorDistances &lt;-<span class="st"> </span><span class="kw">append</span>(poorDistances,<span class="kw">min</span>(<span class="kw">calcDistance</span>(corPoorPeople[i,],corStrmEvents)))
}

richDistances &lt;-<span class="st"> </span><span class="kw">c</span>()
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(corRichPeople[,<span class="dv">1</span>])){
  richDistances &lt;-<span class="st"> </span><span class="kw">append</span>(richDistances,<span class="kw">min</span>(<span class="kw">calcDistance</span>(corRichPeople[i,],corStrmEvents)))
}</code></pre></div>
<p>Now that we have the distance to the nearest weather point we simply do a summary of both the rich and the poor distances.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Convert from latitude/longitutde to km for sanity. </span>
<span class="kw">summary</span>(poorDistances<span class="op">*</span><span class="fl">110.574</span>) </code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##   0.00004   0.02676   0.11175   1.83479   0.47457 178.30054</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(richDistances<span class="op">*</span><span class="fl">110.574</span>)</code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##   0.00001   0.04025   0.13215   0.56362   0.41050 111.15449</code></pre>
<div id="summary" class="section level3 unnumbered">
<h3>Summary</h3>
<p>We can see that the mean distance for rich people is signficiantly closer than the mean distance for poor people. That means on average, can we say that the rich neighborhoods are consistently closer to extreme weather events?</p>
<p>From the rough summary it does indeed.</p>
<p>After looking at histograms it seems that the distances are modeled by one of the heavy tailed solutions. Taking the logorithm allows for a better looking plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(<span class="kw">log</span>(poorDistances<span class="op">*</span><span class="fl">110.574</span>),
     <span class="dt">main=</span><span class="st">&quot;Poor to Nearest Event&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Distance&quot;</span>,
     <span class="dt">breaks =</span> <span class="dv">40</span>)</code></pre></div>
<p><img src="self-studies_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(<span class="kw">log</span>(richDistances<span class="op">*</span><span class="fl">110.574</span>),
     <span class="dt">main=</span><span class="st">&quot;Rich to Nearest Event&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Distance&quot;</span>,
     <span class="dt">breaks =</span> <span class="dv">40</span>)</code></pre></div>
<p><img src="self-studies_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<p>My assumption is that this is the lognormal distribution.</p>
<p>Consider a random variable <span class="math inline">\(U\)</span> having univariate log-normal distribution with parameters <span class="math inline">\(\sigma \in \mathbb{R}_{+}\)</span> <span class="math inline">\(\mu \in \mathbb{R}\)</span>. Have <span class="math inline">\(u \in \mathbb{R}_+\)</span>, then the probability density function of random variable <span class="math inline">\(U\)</span> is defined as  <span class="math display">\[\mathcal{LN}(u; \mu, \sigma) = \frac{1}{u\sigma\sqrt{2\pi}}\exp\left[-\frac{(\ln u - \mu)^2}{2\sigma^2}   \right].\]</span></p>
<p>Now lets compute the log(distance) and check the summary.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">log</span>(poorDistances<span class="op">*</span><span class="fl">110.574</span>))</code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -10.1652  -3.6210  -2.1915  -2.1708  -0.7454   5.1835</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">log</span>(richDistances<span class="op">*</span><span class="fl">110.574</span>))</code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -11.5947  -3.2127  -2.0238  -2.0975  -0.8904   4.7109</code></pre>
<p>We see a mean of -2.0975 for rich, vs -2.1708 for poor.</p>
<p>With the log-normal assumption we can say that the rich people are actually farther away from the extreme events than poor people.</p>
<p>However, is this really the case?</p>
<p>Let’s compare the two mean’s together using the Student’s t-test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Students t-test </span>
<span class="kw">t.test</span>(<span class="kw">log</span>(poorDistances<span class="op">*</span><span class="fl">110.574</span>),<span class="kw">log</span>(richDistances<span class="op">*</span><span class="fl">110.574</span>)) </code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  log(poorDistances * 110.574) and log(richDistances * 110.574)
## t = -0.90295, df = 1189.6, p-value = 0.3667
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.23266887  0.08600527
## sample estimates:
## mean of x mean of y 
## -2.170832 -2.097500</code></pre>
<p>Since our p-value is too large we cannot reject the null hypothesis.</p>
</div>
</div>
<div id="therefore-neither-rich-people-or-poor-people-are-more-likely-to-be-hit-with-extreme-weather-events." class="section level2 unnumbered">
<h2>Therefore neither rich people or poor people are more likely to be hit with extreme weather events.</h2>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ss.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="understanding-the-em-algorithm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["self-studies.pdf", "self-studies.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
